name: Deploy OpenShift Pod
hosts: localhost
tasks:
- name: Create Pod
kubernetes.core.k8s:
definition:
apiVersion: v1
kind: Pod
metadata:
name: "{{ pod_name }}"
namespace: "{{ namespace }}"
spec:
containers:
- name: nginx
image: "{{ image }}"
