---
- name: Install Package
  hosts: all
  become: yes  # Add privilege escalation
  tasks:
    - name: Install package on RedHat-based systems
      yum:
        name: "{{ package }}"
        state: present
      when: ansible_os_family == "RedHat" and package is defined

    - name: Install package on Debian-based systems
      apt:
        name: "{{ package }}"
        state: present
        update_cache: yes  # Good practice to update apt cache
      when: ansible_os_family == "Debian" and package is defined
